Vagrant.configure("2") do |config|

  hostname = ENV["COMPUTERNAME"]
  saltRoot = "../saltstack"

  config.trigger.before :up do
    `powershell cd ..;.\\Create-CredentialsFile.ps1`
  end

  config.trigger.before :reload do
    `powershell cd ..;.\\Create-CredentialsFile.ps1`
  end
  

  config.vm.provision "docker" do |d|
    d.build_image "/vagrant", args: "-t salt-master"
  end
 
  
  
  
	
  config.vm.provision "shell", inline: "/vagrant/host/create_volumes.sh"
  config.vm.provision "shell", inline: "/vagrant/host/run_master_container.sh"

  config.vm.box = "ubuntu/xenial64"

  config.vm.synced_folder "..", "/vagrant"

  # salt
  config.vm.network "forwarded_port", guest:4505, host: 4505
  config.vm.network "forwarded_port", guest:4506, host: 4506
  config.vm.network "forwarded_port", guest:8000, host: 8000
  # support local salt states
  config.vm.synced_folder "#{saltRoot}", "/salt"

  # winrm
  # stop your winrm service if this fails
  config.vm.network "forwarded_port", guest:5985, host: 5985 
  config.vm.network "forwarded_port", guest:5986, host: 5986

  # saltpad
  config.vm.network "forwarded_port", guest:8080, host: 8080

end